#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

if [ -z "$(ls -A /mnt/apps/app/public)" ]; then
    cd /mnt/apps/samsung/promo/
    composer create-project symfony/website-skeleton .
fi

cd /mnt/apps/samsung/promo

if [ -z "$(ls -A /mnt/apps/app/var)" ]; then
    chmod 777 var/ -R
fi

if [ -z "$(ls -A /mnt/apps/app/.env)" ]; then
    cp .env.dist .env
fi

while ! curl http://database:3306/ 2>&1 | grep '52'
do
	>&2 echo "Mysql is unavailable - sleeping"
	sleep 1
done

>&2 echo "Mysql is up - Run migrations"

#Execute queries diff
php bin/console doctrine:schema:update --force

#Seed database
php -d memory_limit=-1 bin/console doctrine:fixtures:load --no-interaction

exec "$@"