version: '3.4'

services:
  http:
    image: httpd:latest
    ports:
      - 80:80
    volumes:
      - ./webapp:/srv:ro
  php:
    image: php:7.2-fpm-alpine
    volumes:
      - ./webapp:/srv:rw
    environment:
      APP_ENV: dev
      XDEBUG_CONFIG: "remote_host=172.0.0.1 remote_enable=on"
      APP_XDEBUG: enabled
      SYMFONY_PHPUNIT_VERSION: 7.4
      APP_AUTO_UPDATE: disabled
    depends_on:
      - db
    links:
      - http:front.test.fr

  db:
    image: mysql:5.7.25
    environment:
      - MYSQL_DATABASE=mybdd
      - MYSQL_USER=bdd
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - database:/var/lib/mysql:rw
      - ./db/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - 3306:3306

  node:
    image: node:8-alpine
    hostname: node.test
    working_dir: /srv
    ports:
      - "8080:8080"
    volumes:
      - ./webapp/:/srv/

volumes:
  database: ~
