#!/bin/bash
# If commit message is a fixup message, ignore it
grep --quiet 'fixup!' "$1" && FIXUP="YES"

TICKET=$(git symbolic-ref HEAD | rev | cut -d/ -f1 | rev | grep -o -E "[A-Z]+-#[0-9]+")
grep --quiet "${TICKET}" "$1" && TICKET_EXISTS="YES"

if [[ -n "${TICKET}" && -z "${TICKET_EXISTS}" && -z "${FIXUP}" ]]; then
    sed -i.bak -e "1s/^/[${TICKET}] /" "$1"
fi
